version: '3.3'

volumes:
  rc-backend-dbdata:

networks:
  default:
    external:
      name: research-coder

services:

  rc-backend-dev:
    container_name: rc-backend
    build: .
    volumes:
      - ./:/var/www/app
    environment:
      - DB_HOST=rc-backend-db
      - DB_PORT=3306
      - COMPOSER_ALLOW_SUPERUSER=1
    env_file: .env.api
    ports:
      - 8000:8000
    user: ${UID:-0}:${GID:-0}
    entrypoint: php artisan serve --host 0.0.0.0 --port 8000

  rc-backend-db-dev:
    container_name: rc-backend-db
    image: mysql:5.7
    volumes:
      - rc-backend-dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=research-coder
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 33061:3306
