version: '2'
services:
  app:
    container_name: rc-api
    image: vectorweb/research-coder-api
    build: ./
    links:
      - database
    env_file:
      - .env
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "MYSQL_DATABASE=research-coder"
    ports:
      - "8080:80"

  database:
    container_name: rc-db
    image: mysql
    volumes:
      - rc-db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=research-coder"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"

volumes:
  rc-db: