FROM vectorapps/php:7.1

WORKDIR /app

COPY composer.* ./
RUN export COMPOSER_ALLOW_SUPERUSER=1 && \
    composer install --no-scripts --no-autoloader

COPY . .

RUN export COMPOSER_ALLOW_SUPERUSER=1 && \
    composer dump-autoload -o

CMD composer dump-autoload -o && php artisan serve --host 0.0.0.0 --port 8000
