
version: '2.1'
services:
  app:
    container_name: rc-api-dev
    image: vectorweb/research-coder-api
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./:/var/www/app
    env_file:
      - .env
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "MYSQL_DATABASE=research-coder"
    ports:
      - "8080:80"

  database:
    container_name: rc-db-dev
    image: mysql
    volumes:
      - rc-db-dev:/var/lib/mysql
    healthcheck:
      test: mysql -u homestead --password=secret -e "exit" research-coder
      interval: 3s
      retries: 3
      timeout: 10s
    environment:
      - "MYSQL_DATABASE=research-coder"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"

volumes:
  rc-db-dev:
