FROM php:7.1

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN mkdir -p /.config/psysh /.composer && \
    chmod -R 777 /.config /.composer

RUN apt-get update -y && apt-get install -y openssl mysql-client zip unzip && \
    docker-php-ext-install pdo pdo_mysql mbstring bcmath

WORKDIR /app

COPY composer.json composer.lock ./
RUN export COMPOSER_ALLOW_SUPERUSER=1 && \
    composer install --no-scripts --no-autoloader

COPY . .

RUN export COMPOSER_ALLOW_SUPERUSER=1 && \
    composer dump-autoload -o

ENTRYPOINT composer dump-autoload -o && php artisan serve --host 0.0.0.0 --port 8000