version: '3.3'

services:

  app:
    container_name: rc-api-dev
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - ./:/app
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - COMPOSER_ALLOW_SUPERUSER=1
    env_file: .env.api
    ports:
      - 8000:8000
    user: ${UID:-0}:${GID:-0}

  database:
    container_name: rc-db-dev
    image: mysql:5.7
    volumes:
      - rc-db-dev:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=research-coder
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 33061:3306

volumes:
  rc-db-dev: