version: '3.3'

volumes:
  rc-backend-dbdata:

networks:
  default:
    external:
      name: research-coder

services:

  rc-backend:
    container_name: rc-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../.keys/rc-auth.key.pub:/.keys/rc-auth.key.pub
      - .:/app
    environment:
      DB_HOST: rc-backend-db
      DB_PORT: 3306
      JWT_PUBLIC_KEY: /.keys/rc-auth.key.pub
      AUTH_API_SECRET: secret
      RABBITMQ_HOST: rc-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    env_file: .env.api
    ports:
      - 8000:8000
    user: ${UID:-0}:${GID:-0}

  rc-backend-db:
    container_name: rc-backend-db-dev
    image: mysql:5.7
    volumes:
      - rc-backend-dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=research-coder
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 33061:3306

  rc-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rc-rabbitmq-dev
    ports:
      - "15672:15672"
      - "5672:5672"